name: Auto Tag, Changelog & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install git-chglog
        run: |
          GIT_CHGLOG_VERSION=$(curl -s https://api.github.com/repos/git-chglog/git-chglog/releases/latest | jq -r '.tag_name')
          wget -q "https://github.com/git-chglog/git-chglog/releases/download/${GIT_CHGLOG_VERSION}/git-chglog_${GIT_CHGLOG_VERSION#v}_linux_amd64.tar.gz"
          tar -xzf git-chglog_${GIT_CHGLOG_VERSION#v}_linux_amd64.tar.gz
          sudo mv git-chglog /usr/local/bin/
          git-chglog --version

      - name: Determine next version
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          NEW_TAG=$(echo $LAST_TAG | awk -F. -v OFS=. '{$NF++; print}')
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New version: $NEW_TAG"

      - name: Generate changelog
        run: |
          git-chglog --next-tag ${NEW_TAG} -o CHANGELOG.md

      - name: Create Git tag
        run: |
          git tag ${NEW_TAG}
          git push origin ${NEW_TAG}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false